// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/pia4java.proto

package pia4java;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PiaConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pia4java.PiaConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string pia_wireguard_server = 1;</code>
     * @return Whether the piaWireguardServer field is set.
     */
    boolean hasPiaWireguardServer();
    /**
     * <code>optional string pia_wireguard_server = 1;</code>
     * @return The piaWireguardServer.
     */
    java.lang.String getPiaWireguardServer();
    /**
     * <code>optional string pia_wireguard_server = 1;</code>
     * @return The bytes for piaWireguardServer.
     */
    com.google.protobuf.ByteString
        getPiaWireguardServerBytes();

    /**
     * <code>optional int32 pia_wireguard_port = 2;</code>
     * @return Whether the piaWireguardPort field is set.
     */
    boolean hasPiaWireguardPort();
    /**
     * <code>optional int32 pia_wireguard_port = 2;</code>
     * @return The piaWireguardPort.
     */
    int getPiaWireguardPort();

    /**
     * <code>optional string pia_username = 3;</code>
     * @return Whether the piaUsername field is set.
     */
    boolean hasPiaUsername();
    /**
     * <code>optional string pia_username = 3;</code>
     * @return The piaUsername.
     */
    java.lang.String getPiaUsername();
    /**
     * <code>optional string pia_username = 3;</code>
     * @return The bytes for piaUsername.
     */
    com.google.protobuf.ByteString
        getPiaUsernameBytes();

    /**
     * <code>optional string pia_password = 4;</code>
     * @return Whether the piaPassword field is set.
     */
    boolean hasPiaPassword();
    /**
     * <code>optional string pia_password = 4;</code>
     * @return The piaPassword.
     */
    java.lang.String getPiaPassword();
    /**
     * <code>optional string pia_password = 4;</code>
     * @return The bytes for piaPassword.
     */
    com.google.protobuf.ByteString
        getPiaPasswordBytes();

    /**
     * <code>optional string target_domain = 5;</code>
     * @return Whether the targetDomain field is set.
     */
    boolean hasTargetDomain();
    /**
     * <code>optional string target_domain = 5;</code>
     * @return The targetDomain.
     */
    java.lang.String getTargetDomain();
    /**
     * <code>optional string target_domain = 5;</code>
     * @return The bytes for targetDomain.
     */
    com.google.protobuf.ByteString
        getTargetDomainBytes();
  }
  /**
   * Protobuf type {@code pia4java.PiaConfig}
   */
  public static final class PiaConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pia4java.PiaConfig)
      PiaConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PiaConfig.newBuilder() to construct.
    private PiaConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PiaConfig() {
      piaWireguardServer_ = "";
      piaUsername_ = "";
      piaPassword_ = "";
      targetDomain_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PiaConfig();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PiaConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              piaWireguardServer_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              piaWireguardPort_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              piaUsername_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              piaPassword_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              targetDomain_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pia4java.Proto.internal_static_pia4java_PiaConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pia4java.Proto.internal_static_pia4java_PiaConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pia4java.Proto.PiaConfig.class, pia4java.Proto.PiaConfig.Builder.class);
    }

    private int bitField0_;
    public static final int PIA_WIREGUARD_SERVER_FIELD_NUMBER = 1;
    private volatile java.lang.Object piaWireguardServer_;
    /**
     * <code>optional string pia_wireguard_server = 1;</code>
     * @return Whether the piaWireguardServer field is set.
     */
    @java.lang.Override
    public boolean hasPiaWireguardServer() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string pia_wireguard_server = 1;</code>
     * @return The piaWireguardServer.
     */
    @java.lang.Override
    public java.lang.String getPiaWireguardServer() {
      java.lang.Object ref = piaWireguardServer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          piaWireguardServer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pia_wireguard_server = 1;</code>
     * @return The bytes for piaWireguardServer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPiaWireguardServerBytes() {
      java.lang.Object ref = piaWireguardServer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        piaWireguardServer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PIA_WIREGUARD_PORT_FIELD_NUMBER = 2;
    private int piaWireguardPort_;
    /**
     * <code>optional int32 pia_wireguard_port = 2;</code>
     * @return Whether the piaWireguardPort field is set.
     */
    @java.lang.Override
    public boolean hasPiaWireguardPort() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 pia_wireguard_port = 2;</code>
     * @return The piaWireguardPort.
     */
    @java.lang.Override
    public int getPiaWireguardPort() {
      return piaWireguardPort_;
    }

    public static final int PIA_USERNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object piaUsername_;
    /**
     * <code>optional string pia_username = 3;</code>
     * @return Whether the piaUsername field is set.
     */
    @java.lang.Override
    public boolean hasPiaUsername() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string pia_username = 3;</code>
     * @return The piaUsername.
     */
    @java.lang.Override
    public java.lang.String getPiaUsername() {
      java.lang.Object ref = piaUsername_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          piaUsername_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pia_username = 3;</code>
     * @return The bytes for piaUsername.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPiaUsernameBytes() {
      java.lang.Object ref = piaUsername_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        piaUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PIA_PASSWORD_FIELD_NUMBER = 4;
    private volatile java.lang.Object piaPassword_;
    /**
     * <code>optional string pia_password = 4;</code>
     * @return Whether the piaPassword field is set.
     */
    @java.lang.Override
    public boolean hasPiaPassword() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string pia_password = 4;</code>
     * @return The piaPassword.
     */
    @java.lang.Override
    public java.lang.String getPiaPassword() {
      java.lang.Object ref = piaPassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          piaPassword_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pia_password = 4;</code>
     * @return The bytes for piaPassword.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPiaPasswordBytes() {
      java.lang.Object ref = piaPassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        piaPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGET_DOMAIN_FIELD_NUMBER = 5;
    private volatile java.lang.Object targetDomain_;
    /**
     * <code>optional string target_domain = 5;</code>
     * @return Whether the targetDomain field is set.
     */
    @java.lang.Override
    public boolean hasTargetDomain() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string target_domain = 5;</code>
     * @return The targetDomain.
     */
    @java.lang.Override
    public java.lang.String getTargetDomain() {
      java.lang.Object ref = targetDomain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetDomain_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string target_domain = 5;</code>
     * @return The bytes for targetDomain.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTargetDomainBytes() {
      java.lang.Object ref = targetDomain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetDomain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, piaWireguardServer_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, piaWireguardPort_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, piaUsername_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, piaPassword_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, targetDomain_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, piaWireguardServer_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, piaWireguardPort_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, piaUsername_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, piaPassword_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, targetDomain_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pia4java.Proto.PiaConfig)) {
        return super.equals(obj);
      }
      pia4java.Proto.PiaConfig other = (pia4java.Proto.PiaConfig) obj;

      if (hasPiaWireguardServer() != other.hasPiaWireguardServer()) return false;
      if (hasPiaWireguardServer()) {
        if (!getPiaWireguardServer()
            .equals(other.getPiaWireguardServer())) return false;
      }
      if (hasPiaWireguardPort() != other.hasPiaWireguardPort()) return false;
      if (hasPiaWireguardPort()) {
        if (getPiaWireguardPort()
            != other.getPiaWireguardPort()) return false;
      }
      if (hasPiaUsername() != other.hasPiaUsername()) return false;
      if (hasPiaUsername()) {
        if (!getPiaUsername()
            .equals(other.getPiaUsername())) return false;
      }
      if (hasPiaPassword() != other.hasPiaPassword()) return false;
      if (hasPiaPassword()) {
        if (!getPiaPassword()
            .equals(other.getPiaPassword())) return false;
      }
      if (hasTargetDomain() != other.hasTargetDomain()) return false;
      if (hasTargetDomain()) {
        if (!getTargetDomain()
            .equals(other.getTargetDomain())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPiaWireguardServer()) {
        hash = (37 * hash) + PIA_WIREGUARD_SERVER_FIELD_NUMBER;
        hash = (53 * hash) + getPiaWireguardServer().hashCode();
      }
      if (hasPiaWireguardPort()) {
        hash = (37 * hash) + PIA_WIREGUARD_PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPiaWireguardPort();
      }
      if (hasPiaUsername()) {
        hash = (37 * hash) + PIA_USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getPiaUsername().hashCode();
      }
      if (hasPiaPassword()) {
        hash = (37 * hash) + PIA_PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPiaPassword().hashCode();
      }
      if (hasTargetDomain()) {
        hash = (37 * hash) + TARGET_DOMAIN_FIELD_NUMBER;
        hash = (53 * hash) + getTargetDomain().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pia4java.Proto.PiaConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pia4java.Proto.PiaConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pia4java.Proto.PiaConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pia4java.Proto.PiaConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pia4java.Proto.PiaConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pia4java.Proto.PiaConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pia4java.Proto.PiaConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pia4java.Proto.PiaConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pia4java.Proto.PiaConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pia4java.Proto.PiaConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pia4java.Proto.PiaConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pia4java.Proto.PiaConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pia4java.Proto.PiaConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pia4java.PiaConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pia4java.PiaConfig)
        pia4java.Proto.PiaConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pia4java.Proto.internal_static_pia4java_PiaConfig_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pia4java.Proto.internal_static_pia4java_PiaConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pia4java.Proto.PiaConfig.class, pia4java.Proto.PiaConfig.Builder.class);
      }

      // Construct using pia4java.Proto.PiaConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        piaWireguardServer_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        piaWireguardPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        piaUsername_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        piaPassword_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        targetDomain_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pia4java.Proto.internal_static_pia4java_PiaConfig_descriptor;
      }

      @java.lang.Override
      public pia4java.Proto.PiaConfig getDefaultInstanceForType() {
        return pia4java.Proto.PiaConfig.getDefaultInstance();
      }

      @java.lang.Override
      public pia4java.Proto.PiaConfig build() {
        pia4java.Proto.PiaConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pia4java.Proto.PiaConfig buildPartial() {
        pia4java.Proto.PiaConfig result = new pia4java.Proto.PiaConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.piaWireguardServer_ = piaWireguardServer_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.piaWireguardPort_ = piaWireguardPort_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.piaUsername_ = piaUsername_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.piaPassword_ = piaPassword_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.targetDomain_ = targetDomain_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pia4java.Proto.PiaConfig) {
          return mergeFrom((pia4java.Proto.PiaConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pia4java.Proto.PiaConfig other) {
        if (other == pia4java.Proto.PiaConfig.getDefaultInstance()) return this;
        if (other.hasPiaWireguardServer()) {
          bitField0_ |= 0x00000001;
          piaWireguardServer_ = other.piaWireguardServer_;
          onChanged();
        }
        if (other.hasPiaWireguardPort()) {
          setPiaWireguardPort(other.getPiaWireguardPort());
        }
        if (other.hasPiaUsername()) {
          bitField0_ |= 0x00000004;
          piaUsername_ = other.piaUsername_;
          onChanged();
        }
        if (other.hasPiaPassword()) {
          bitField0_ |= 0x00000008;
          piaPassword_ = other.piaPassword_;
          onChanged();
        }
        if (other.hasTargetDomain()) {
          bitField0_ |= 0x00000010;
          targetDomain_ = other.targetDomain_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pia4java.Proto.PiaConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pia4java.Proto.PiaConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object piaWireguardServer_ = "";
      /**
       * <code>optional string pia_wireguard_server = 1;</code>
       * @return Whether the piaWireguardServer field is set.
       */
      public boolean hasPiaWireguardServer() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string pia_wireguard_server = 1;</code>
       * @return The piaWireguardServer.
       */
      public java.lang.String getPiaWireguardServer() {
        java.lang.Object ref = piaWireguardServer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            piaWireguardServer_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pia_wireguard_server = 1;</code>
       * @return The bytes for piaWireguardServer.
       */
      public com.google.protobuf.ByteString
          getPiaWireguardServerBytes() {
        java.lang.Object ref = piaWireguardServer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          piaWireguardServer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pia_wireguard_server = 1;</code>
       * @param value The piaWireguardServer to set.
       * @return This builder for chaining.
       */
      public Builder setPiaWireguardServer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        piaWireguardServer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pia_wireguard_server = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPiaWireguardServer() {
        bitField0_ = (bitField0_ & ~0x00000001);
        piaWireguardServer_ = getDefaultInstance().getPiaWireguardServer();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pia_wireguard_server = 1;</code>
       * @param value The bytes for piaWireguardServer to set.
       * @return This builder for chaining.
       */
      public Builder setPiaWireguardServerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        piaWireguardServer_ = value;
        onChanged();
        return this;
      }

      private int piaWireguardPort_ ;
      /**
       * <code>optional int32 pia_wireguard_port = 2;</code>
       * @return Whether the piaWireguardPort field is set.
       */
      @java.lang.Override
      public boolean hasPiaWireguardPort() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 pia_wireguard_port = 2;</code>
       * @return The piaWireguardPort.
       */
      @java.lang.Override
      public int getPiaWireguardPort() {
        return piaWireguardPort_;
      }
      /**
       * <code>optional int32 pia_wireguard_port = 2;</code>
       * @param value The piaWireguardPort to set.
       * @return This builder for chaining.
       */
      public Builder setPiaWireguardPort(int value) {
        bitField0_ |= 0x00000002;
        piaWireguardPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pia_wireguard_port = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPiaWireguardPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        piaWireguardPort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object piaUsername_ = "";
      /**
       * <code>optional string pia_username = 3;</code>
       * @return Whether the piaUsername field is set.
       */
      public boolean hasPiaUsername() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string pia_username = 3;</code>
       * @return The piaUsername.
       */
      public java.lang.String getPiaUsername() {
        java.lang.Object ref = piaUsername_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            piaUsername_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pia_username = 3;</code>
       * @return The bytes for piaUsername.
       */
      public com.google.protobuf.ByteString
          getPiaUsernameBytes() {
        java.lang.Object ref = piaUsername_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          piaUsername_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pia_username = 3;</code>
       * @param value The piaUsername to set.
       * @return This builder for chaining.
       */
      public Builder setPiaUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        piaUsername_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pia_username = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPiaUsername() {
        bitField0_ = (bitField0_ & ~0x00000004);
        piaUsername_ = getDefaultInstance().getPiaUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pia_username = 3;</code>
       * @param value The bytes for piaUsername to set.
       * @return This builder for chaining.
       */
      public Builder setPiaUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        piaUsername_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object piaPassword_ = "";
      /**
       * <code>optional string pia_password = 4;</code>
       * @return Whether the piaPassword field is set.
       */
      public boolean hasPiaPassword() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string pia_password = 4;</code>
       * @return The piaPassword.
       */
      public java.lang.String getPiaPassword() {
        java.lang.Object ref = piaPassword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            piaPassword_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pia_password = 4;</code>
       * @return The bytes for piaPassword.
       */
      public com.google.protobuf.ByteString
          getPiaPasswordBytes() {
        java.lang.Object ref = piaPassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          piaPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pia_password = 4;</code>
       * @param value The piaPassword to set.
       * @return This builder for chaining.
       */
      public Builder setPiaPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        piaPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pia_password = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPiaPassword() {
        bitField0_ = (bitField0_ & ~0x00000008);
        piaPassword_ = getDefaultInstance().getPiaPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pia_password = 4;</code>
       * @param value The bytes for piaPassword to set.
       * @return This builder for chaining.
       */
      public Builder setPiaPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        piaPassword_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object targetDomain_ = "";
      /**
       * <code>optional string target_domain = 5;</code>
       * @return Whether the targetDomain field is set.
       */
      public boolean hasTargetDomain() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string target_domain = 5;</code>
       * @return The targetDomain.
       */
      public java.lang.String getTargetDomain() {
        java.lang.Object ref = targetDomain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            targetDomain_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string target_domain = 5;</code>
       * @return The bytes for targetDomain.
       */
      public com.google.protobuf.ByteString
          getTargetDomainBytes() {
        java.lang.Object ref = targetDomain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetDomain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string target_domain = 5;</code>
       * @param value The targetDomain to set.
       * @return This builder for chaining.
       */
      public Builder setTargetDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        targetDomain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string target_domain = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetDomain() {
        bitField0_ = (bitField0_ & ~0x00000010);
        targetDomain_ = getDefaultInstance().getTargetDomain();
        onChanged();
        return this;
      }
      /**
       * <code>optional string target_domain = 5;</code>
       * @param value The bytes for targetDomain to set.
       * @return This builder for chaining.
       */
      public Builder setTargetDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        targetDomain_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pia4java.PiaConfig)
    }

    // @@protoc_insertion_point(class_scope:pia4java.PiaConfig)
    private static final pia4java.Proto.PiaConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pia4java.Proto.PiaConfig();
    }

    public static pia4java.Proto.PiaConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PiaConfig>
        PARSER = new com.google.protobuf.AbstractParser<PiaConfig>() {
      @java.lang.Override
      public PiaConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PiaConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PiaConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PiaConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pia4java.Proto.PiaConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pia4java_PiaConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pia4java_PiaConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035src/main/proto/pia4java.proto\022\010pia4jav" +
      "a\"\210\001\n\tPiaConfig\022\034\n\024pia_wireguard_server\030" +
      "\001 \001(\t\022\032\n\022pia_wireguard_port\030\002 \001(\005\022\024\n\014pia" +
      "_username\030\003 \001(\t\022\024\n\014pia_password\030\004 \001(\t\022\025\n" +
      "\rtarget_domain\030\005 \001(\tB\021\n\010pia4javaB\005Proto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pia4java_PiaConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pia4java_PiaConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pia4java_PiaConfig_descriptor,
        new java.lang.String[] { "PiaWireguardServer", "PiaWireguardPort", "PiaUsername", "PiaPassword", "TargetDomain", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
